# Generated by Django 5.1.7 on 2025-03-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_loan_return_date_alter_loan_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together=set(),
        ),
    ]
