# Generated by Django 5.1.7 on 2025-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_loan_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
